server {
  listen 8080;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  add_header X-Content-Type-Options nosniff always;
  add_header X-Frame-Options DENY always;
  add_header Referrer-Policy no-referrer always;

  location = /healthz {
    access_log off;
    default_type application/json;
    return 200 '{"service":"edge-nginx","status":"ok"}\n';
  }

  location = /platform-api.openapi.yaml {
    default_type application/yaml;
    try_files $uri =404;
  }

  location /api/ {
    proxy_http_version 1.1;
    proxy_hide_header Referrer-Policy;
    proxy_hide_header X-Content-Type-Options;
    proxy_hide_header X-Frame-Options;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Request-ID $request_id;
    proxy_pass http://platform-api:8080;
  }

  location = /readyz {
    proxy_http_version 1.1;
    proxy_hide_header Referrer-Policy;
    proxy_hide_header X-Content-Type-Options;
    proxy_hide_header X-Frame-Options;
    proxy_set_header Host $host;
    proxy_set_header X-Request-ID $request_id;
    proxy_pass http://platform-api:8080/readyz;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
